=== satishayyaswami/tsi-los-service/web/WEB-INF/validator/proto_post_candidate_score_data.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "_data": {
      "type": "object"
    },
    "s-code": {
      "type": "string"
    },
    "candidate-id": {
      "type": "string"
    },
    "client-user-id": {
      "type": "string"
    },
    "_func": {
      "type": "string"
    },
    "candidate-name": {
      "type": "string"
    }
  },
  "required": [
    "_data",
    "s-code",
    "candidate-id",
    "client-user-id",
    "_func",
    "candidate-name"
  ]
}

=== satishayyaswami/tsi-los-service/tests/jobs/proto-post-candidate-score.json
{
  "_func": "post_candidate_score_data",
  "s-code": "senior",
  "client-user-id": "1001",
  "candidate-id": "123",
  "candidate-name": "abc",
  "_data": {
    "age": 78,
    "health": "low_risk",
    "work-environment":"excellent",
    "oral_communication":"excellent",
    "written_communication": "excellent",
    "professional_behavior": "excellent"
  }
}
